### ISSUE TITLE
Razorpay "pay" button doesn't work

### ISSUE THREAD

**Issue by faizan15** [codermursalin/MS-WEB-SHOP#1]
On clicking "Pay", error rises as AxiosError: ERR_BAD_RESPONSE and Failed to load resource: the server responded with a status of 500 (Internal Server Error). 
The second error refers to api call towards createorder.

**Comment by codermursalin** [comment]
I have cheacked it working fine.
If you are using my code you need Razorpay_API_KEY and Razorpay_Secret_Key to perform API call
